package com.interniq.notification;

public enum EmailNotificationType {
    OFFER_LETTER_SENT,
    INTERVIEW_SCHEDULED,
    INTERVIEW_RESCHEDULED,
    INTERVIEW_CANCELLED,
    CANDIDATE_SELECTED,
    CANDIDATE_REJECTED,
    CANDIDATE_SHORTLISTED,
    RESUME_SCREENING_COMPLETED,
    DEPARTMENT_ASSIGNED,
    MANAGER_ASSIGNED,
    INTERN_ONBOARDED,
    INTERNSHIP_START_REMINDER,
    INTERNSHIP_COMPLETION
}
